### ISSUE TITLE
dizayn

### ISSUE THREAD

**Issue by abdullajon8111** [JamshidDev/EduStat.uz#1]
O'zbekiston kartasi turgan section ikki chetidan ajralib turishi. xuddi tepasidagi section kabi
![image](https://github.com/user-attachments/assets/fdff9eca-36f5-4541-bff1-46e339adcf69)
taxminan shunday masofada. undan keyin height 100vh berilgan width ham 100% berilgan full screen bilan birxil height ni ham qisqartirish kerak

**Comment by JamshidDev** [comment]
done
