### ISSUE TITLE
yandex map

### ISSUE THREAD

**Issue by abdullajon8111** [JamshidDev/EduStat.uz#5]
`<iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3Af253b8b07b44514ba7b135e21b06bb09af406b777a8ee7bc529c217b7cc75473&amp;source=constructor" width="605" height="393" frameborder="0"></iframe>`

karta turgan joyga footerdagi shu kodni qo'ysangiz token so'ramidi 401 bo'lib qomaydi

![image](https://github.com/user-attachments/assets/af23b164-5d07-4dd8-beef-8e892b406ea9)

**Comment by JamshidDev** [comment]
done
