### ISSUE TITLE
uzb map

### ISSUE THREAD

**Issue by abdullajon8111** [JamshidDev/EduStat.uz#6]
![image](https://github.com/user-attachments/assets/84b754c3-b10b-4657-8f95-cf93457ee46c)

![image](https://github.com/user-attachments/assets/7c4012c9-332b-4f5c-b62c-320210eb2270)

**kartalar o'rtada turgani yaxshi
tepaga yopishib qopti**

**Comment by JamshidDev** [comment]
done
